"""Experimental Hyperdimensional Space Computing kernels.

Modules in this package are research-only until their explicit promotion gate
is complete. Production trace retrieval continues to use its separately named
baseline engine.
"""

from ssa.hdsc.active_space import (
    MODEL_ID as H2_MODEL_ID,
)
from ssa.hdsc.active_space import (
    SUPPORT_METRIC,
    H2ActiveCluster,
    H2Audit,
    H2Candidate,
    H2Config,
    H2GainBounds,
    H2Result,
    H2State,
    bounded_active_shadow_step,
    state_total_variation,
)
from ssa.hdsc.archive import (
    ArchiveConfig,
    ArchiveEntry,
    BehaviorDescriptor,
    ParetoArchive,
    ScoreVector,
)
from ssa.hdsc.directed_transport import (
    MODEL_ID as H1D_MODEL_ID,
)
from ssa.hdsc.directed_transport import (
    HDSCH1DAudit,
    HDSCH1DParameters,
    HDSCH1DResult,
    build_directed_rates,
    directed_generator,
    propagate_directed,
)
from ssa.hdsc.hypervector import (
    PackedHypervector,
    bipolar_dot,
    hamming_distance,
    semantic_random,
    similarity,
)
from ssa.hdsc.hypervector import (
    bind as bind_hypervector,
)
from ssa.hdsc.hypervector import (
    bundle as bundle_hypervector,
)
from ssa.hdsc.hypervector import (
    permute as permute_hypervector,
)
from ssa.hdsc.hypervector import (
    unbind as unbind_hypervector,
)
from ssa.hdsc.interpreter import (
    BudgetExceeded,
    EffectBoundaryError,
    ExecBudget,
    ExecContext,
    ExecResult,
    ExecutionValue,
    InterpreterError,
    StaticBudgetReport,
    execute,
    static_budget_gate,
)
from ssa.hdsc.operators import (
    AFF,
    CTX,
    EFF,
    EV,
    GR,
    HV,
    MEM,
    PRIMITIVE_REGISTRY,
    REL,
    SC,
    Base,
    Coll,
    Diff,
    Fn,
    Operator,
    OperatorRegistry,
    Purity,
    Signature,
    Ty,
    Z,
    build_primitive_registry,
)
from ssa.hdsc.program import (
    CAPABILITY_ENVELOPE,
    HASH_NAMESPACE,
    SEARCH_SCOPE,
    LinearityError,
    Node,
    Program,
    ProgramInput,
    ProgramTypeError,
    check_linearity,
    iter_nodes,
    node_digest,
    program_digest,
    static_cost,
    subtree_digests,
    type_check,
)
from ssa.hdsc.program import (
    CLAIM_LEVEL as SEOS_CLAIM_LEVEL,
)
from ssa.hdsc.program import (
    MODEL_ID as SEOS_MODEL_ID,
)
from ssa.hdsc.transport import (
    CLAIM_LEVEL,
    MICROSTATE_STATUS,
    MODEL_ID,
    MODELED_SCALE,
    HDSCH1Audit,
    HDSCH1Parameters,
    HDSCH1Result,
    HDSCInvariantError,
    allocate_source_mass,
    build_semantic_conductance,
    graph_laplacian,
    propagate,
    run_shadow,
)
from ssa.hdsc.variation import (
    VariationError,
    apply_random_variation,
    crossover_subgraph,
    derive_rng,
    ensure_type,
    mutate_delete,
    mutate_insert,
    mutate_param,
    mutate_point,
)

__all__ = [
    "AFF",
    "CAPABILITY_ENVELOPE",
    "CLAIM_LEVEL",
    "CTX",
    "EFF",
    "EV",
    "GR",
    "H1D_MODEL_ID",
    "H2_MODEL_ID",
    "HASH_NAMESPACE",
    "HV",
    "MEM",
    "MICROSTATE_STATUS",
    "MODELED_SCALE",
    "MODEL_ID",
    "PRIMITIVE_REGISTRY",
    "REL",
    "SC",
    "SEARCH_SCOPE",
    "SEOS_CLAIM_LEVEL",
    "SEOS_MODEL_ID",
    "SUPPORT_METRIC",
    "ArchiveConfig",
    "ArchiveEntry",
    "Base",
    "BehaviorDescriptor",
    "BudgetExceeded",
    "Coll",
    "Diff",
    "EffectBoundaryError",
    "ExecBudget",
    "ExecContext",
    "ExecResult",
    "ExecutionValue",
    "Fn",
    "H2ActiveCluster",
    "H2Audit",
    "H2Candidate",
    "H2Config",
    "H2GainBounds",
    "H2Result",
    "H2State",
    "HDSCH1Audit",
    "HDSCH1DAudit",
    "HDSCH1DParameters",
    "HDSCH1DResult",
    "HDSCH1Parameters",
    "HDSCH1Result",
    "HDSCInvariantError",
    "InterpreterError",
    "LinearityError",
    "Node",
    "Operator",
    "OperatorRegistry",
    "PackedHypervector",
    "ParetoArchive",
    "Program",
    "ProgramInput",
    "ProgramTypeError",
    "Purity",
    "ScoreVector",
    "Signature",
    "StaticBudgetReport",
    "Ty",
    "VariationError",
    "Z",
    "allocate_source_mass",
    "apply_random_variation",
    "bind_hypervector",
    "bipolar_dot",
    "bounded_active_shadow_step",
    "build_directed_rates",
    "build_primitive_registry",
    "build_semantic_conductance",
    "bundle_hypervector",
    "check_linearity",
    "crossover_subgraph",
    "derive_rng",
    "directed_generator",
    "ensure_type",
    "execute",
    "graph_laplacian",
    "hamming_distance",
    "iter_nodes",
    "mutate_delete",
    "mutate_insert",
    "mutate_param",
    "mutate_point",
    "node_digest",
    "permute_hypervector",
    "program_digest",
    "propagate",
    "propagate_directed",
    "run_shadow",
    "semantic_random",
    "similarity",
    "state_total_variation",
    "static_budget_gate",
    "static_cost",
    "subtree_digests",
    "type_check",
    "unbind_hypervector",
]
